### ISSUE TITLE
How can create a real value CSV from a csvpp input file?

### ISSUE THREAD

**Issue by halloleo** [patrickomatic/csv-plus-plus#62]
Maybe I just overlooked it, but I  cannot compile a `.csvpp` file into a real proper "value" CSV.

### Example:

The `.csvpp` input:

```
what,number
banana,13
apple,12
peach,2
SUM,"=SUM(B1,B3)"
```

Expected real CSV output:

```
what,number
banana,13
apple,12
peach,2
SUM,27
```

I don't manage to get that output. Am I missing a command line option?

**Comment by patrickomatic** [comment]
yeah so it doesn't quite work that way - csv++ doesn't provide any kind of spreadsheet "engine" or whatever you'd call the part that does the calculations and evaluations.  The idea is more that you use csv++ for the structure of your spreadsheet (the complex formulas, fills, headers, etc) but then the values are still inputted via the spreadsheet program you use.  

Does this make sense? I've been meaning to write more comprehensive documentation, I'll make sure to create a chapter around design philosophies and how you'd use this thing.  Also if it's helpful I've been building out [some examples](https://github.com/patrickomatic/csvpp-examples).

**Comment by halloleo** [comment]
Thanks for this. 

Makes total sense. -- However this renders `csvpp` rather pointless for my use case, because that's all I need: A CLI tool which converts CSV-like files containing formulas into real CSVs.

Do you have any idea what tool can do this?

***
PS: Also, please let me gently mention, that IMHO the name "**csvpp**" feels a little bit misleading, because the way I understand it none of the files  `csvpp` deals with (neither input nor output) are real CSV files...

**Comment by patrickomatic** [comment]
> because the way I understand it none of the files csvpp deals with (neither input nor output) are real CSV files...

Hmm can you tell me more what you mean by this? It definitely does produce valid CSV

**Comment by halloleo** [comment]
Sorry for the late response, @patrickomatic 

> > because the way I understand it, none of the files csvpp deals with (neither input nor output) are real CSV files...
> 
> Hmm can you tell me more what you mean by this? It definitely does produce valid CSV

Here's what I mean: CSVs _normally_ contain just _values_, like

```
date,temp_min,temp_max 
2023-03-12,16,28.5
2023-03-13,15.1,23
2023-03-14,15.9,26.2
2023-03-15,16.2,29.1
```

CSVs with formulas, like

```
date,temp_min,temp_max,temp_avg
2023-03-12,16,28.5,=(B2+C2)/2
2023-03-13,15.1,23,=(B3+C3)/2
2023-03-14,15.9,26.2,=(B4+C4)/2
2023-03-15,16.2,29.1,=(B5+C5)/2
```

are _syntactically_ CSVs for sure (they are literally comma-separated-value files), but in practice, nobody can use them. To use them for printing or in a data pipeline or what else they need to be _converted_ to a value-based file.

And I think it would be very, very cool if csv-plus-plus could do just that! 😃  

Hope this makes it clearer.
